# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 8888:5432
