# hatch shell

[project]
name = "ironcore-alloy-examples"
authors = [{ name = "IronCore Labs", email = "info@ironcorelabs.com" }]
requires-python = ">=3.7"
dependencies = ["ironcore-alloy"]
dynamic = ["version"]
