[workspace]
members = ["core"]
default-members = ["core"]
resolver = "2"

# used to create the smallest cdylib binary we can to ship with the library in each ecosystem.
# 6.9M vs 1.5M in initial testing. Can further have `strip` (the Unix utility) run on it to save ~0.2 MB more.
# WARNING: be careful changing this, since downstream integration tests (in "core/tests") depend on this profile.
[profile.release]
opt-level = 3       # Check 'z' sometimes in case much smaller. Initial testing showed 0.1M size difference but 25% performance hit, so 3 is better.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = 'debuginfo'
