[package]
name = "ironcore-alloy"
version = "0.9.2-pre.19"
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10" }
aes-siv = { version = "0.7" }
async-trait = "0.1.74"
base64 = "0.21"
base64_type = { git = "https://github.com/IronCoreLabs/base64_type", version = "0.1.0" }
bytes = { version = "1.4.0", features = ["serde"] }
futures = "0.3.29"
hmac = { version = "0.12.1", features = ["std"] }
ironcore-documents = { git = "https://github.com/IronCoreLabs/ironcore-documents.git", rev = "76e2e20fe97e15e27f3d6146562f054144977103" }
itertools = "0.11"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
protobuf = { version = "3.3", features = ["with-bytes"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
ring = "0.16.20"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["float_roundtrip"] }
thiserror = "1.0.50"
uniffi = { git = "https://github.com/bendk/uniffi-rs.git", features = [
    "cli",
    "tokio",
], branch = "foreign-trait-interfaces-opt-in" }
z85 = "3.0.5"

[dev-dependencies]
approx = "0.5.1"
ascii85 = "0.2.1"
assertables = "7.0.1"
base64 = "0.21.5"
base85 = "2.0.0"
camino = "1.1"
criterion = { version = "0.5", features = ["async_tokio"] }
hex = "0.4.3"
hex-literal = "0.4.1"
lazy_static = "1.4"
proptest = "1.2.0"
tokio = { version = "1.33", features = ["macros", "rt-multi-thread"] }
uniffi = { git = "https://github.com/bendk/uniffi-rs.git", features = [
    "bindgen-tests",
], branch = "foreign-trait-interfaces-opt-in" }
uniffi_bindgen = { git = "https://github.com/bendk/uniffi-rs.git", branch = "foreign-trait-interfaces-opt-in" }
z85 = "3.0.5"

[features]
integration_tests = []

[[bench]]
name = "ironcore_alloy_bench"
path = "benches/ironcore_alloy_bench.rs"
harness = false

# This is needed to allow extra options to be passed to criterion
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false
crate-type = ["cdylib", "lib"]
name = "ironcore_alloy"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

# used to create the smallest cdylib binary we can to ship with the library in each ecosystem.
# 6.9M vs 1.5M in initial testing. Can further have `strip` (the Unix utility) run on it to save ~0.2 MB more.
# WARNING: be careful changing this, since downstream integration tests (in "core/tests") depend on this profile.
[profile.release]
opt-level = 3       # Check 'z' sometimes in case much smaller. Initial testing showed 0.1M size difference but 25% performance hit, so 3 is better.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = 'debuginfo'
