# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  commands:
  # install rust. If we automate/otherwise committing the generated python module we can avoid rust at all and
  # only would need to install hatch here. Doc builds would then be a few seconds instead of a few minutes.
  - ./python/ironcore-alloy/rust-toolchain-from-file.sh
  - ~/.cargo/bin/cargo b --release
  - ~/.cargo/bin/cargo run --bin uniffi-bindgen generate --library ./target/release/libironcore_alloy.so --language python  --out-dir python/ironcore-alloy/ironcore_alloy
  - pip install -v "hatch==1.14.1"
  # actual doc building part
  # Switched from hatch run docs:buildRtd because ReadTheDocs was having issues with a hanging --filter somehow
  - cd python/ironcore-alloy && hatch env run -e docs buildRtd
