# hatch shell

[project]
name = "elasticsearch-example"
authors = [{ name = "IronCore Labs", email = "info@ironcorelabs.com" }]
requires-python = ">=3.8"
dependencies = [
    "ironcore-alloy>=0.10.3,<0.11",
    "elasticsearch==8.12.0",
    "sentence_transformers==2.3.1",
]
dynamic = ["version"]
