# hatch shell

[project]
name = "opensearch-example"
authors = [{ name = "IronCore Labs", email = "info@ironcorelabs.com" }]
requires-python = ">=3.9"
dependencies = [
    "ironcore-alloy>=0.11.2,<0.12",
    "opensearch-py==2.4.2",
    "sentence_transformers==2.3.1",
]
dynamic = ["version"]
