[package]
name = "ironcore-alloy-simple-roundtrip"
version = "0.1.0"
edition = "2021"

[dependencies]
ironcore-alloy = "0.12.0"
serde = "1"
serde_json = "1.0.108"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "time",
    "sync",
    "macros",
] }
