# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    # install rust
    - ./core/python/cloaked-ai/rust-toolchain-from-file.sh
    - cargo b --release
    - cargo run --bin uniffi-bindgen generate --library ../target/release/libcloaked_ai.so --language python  --out-dir python/cloaked-ai/cloaked_ai
    # actual doc building part
    - pip install -v "hatch==1.7.0"
    - cd core/python/cloaked-ai && hatch run docs:build --site-dir $READTHEDOCS_OUTPUT/html

   
