# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    # these rust sections are mostly cribbed from our github action https://github.com/IronCoreLabs/rust-toolchain/blob/main/action.yml
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
    - ./rust-toolchain-from-file.sh
    # actual doc building part
    - pip install -v "hatch==1.7.0"
    - cd core/python/cloaked-ai && hatch run docs:build --site-dir $READTHEDOCS_OUTPUT/html

   
